---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gigso/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R helpers $DEPLOYPATH
    - /bin/cp -R actions $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
