import BaseComponent from '../base-component.js';
import UkuleleSongLibrary from '../../ukulele-song-library.js';
import ChordLibrary from '../../chord-library.js';
import ChordDiagram from '../chord-diagram/chord-diagram.js';

export default class SongSheet extends BaseComponent {
    constructor() {
        const template = `
            <div class="song-sheet-container">
                <div class="sheet-header no-print">
                    <button class="back-btn" id="back-search">← Back to Search</button>
                    <div class="sheet-actions">
                        <button class="share-btn" id="share-btn">🔗 Share</button>
                        <button class="print-btn" id="print-btn">🖨️ Print</button>
                        <button class="fullscreen-btn" id="fullscreen-btn">⛶ Fullscreen</button>
                    </div>
                </div>
                
                <div class="song-sheet" id="song-content">
                    <!-- Song content will be populated here -->
                </div>
                
                <div class="sheet-footer no-print">
                    <p>Generated by Unclelele • <a href="#" id="gigso-link">Try the Gigso App</a></p>
                </div>
                
                <!-- Print-only footer -->
                <div class="print-only-footer print-only">
                    <div class="print-footer-content">
                        <span class="print-url">unclelele.com</span>
                        <span class="print-separator">•</span>
                        <span class="print-branding">Generated by Unclelele & Gigso</span>
                    </div>
                </div>
            </div>
        `;
        
        const styles = `
            .song-sheet-container {
                background: white;
                margin: 20px 0;
                box-shadow: 0 4px 20px rgba(0,0,0,0.1);
                border-radius: 15px;
                overflow: hidden;
            }
            
            .sheet-header {
                background: var(--unclelele-secondary, #98D8C8);
                padding: 20px 30px;
                display: flex;
                justify-content: space-between;
                align-items: center;
                flex-wrap: wrap;
                gap: 15px;
            }
            
            .back-btn, .print-btn, .fullscreen-btn, .share-btn {
                background: white;
                color: var(--unclelele-primary, #2E8B57);
                border: none;
                padding: 10px 20px;
                border-radius: 8px;
                font-weight: bold;
                cursor: pointer;
                transition: all 0.2s;
                margin-right: 10px;
            }
            
            .back-btn:hover, .print-btn:hover, .fullscreen-btn:hover, .share-btn:hover {
                transform: translateY(-2px);
                box-shadow: 0 4px 12px rgba(46, 139, 87, 0.3);
            }
            
            .print-btn {
                background: var(--unclelele-accent, #F7931E);
                color: white;
            }
            
            .print-btn:hover {
                box-shadow: 0 4px 12px rgba(247, 147, 30, 0.3);
            }
            
            .share-btn {
                background: #3B82F6;
                color: white;
            }
            
            .share-btn:hover {
                box-shadow: 0 4px 12px rgba(59, 130, 246, 0.3);
            }
            
            .song-sheet {
                padding: 40px;
                line-height: 1.6;
                font-family: 'Georgia', serif;
                background: white;
                min-height: calc(11in - 2in); /* Letter size minus margins */
                max-width: 8.5in;
                margin: 0 auto;
            }
            
            .song-header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 2px solid var(--unclelele-primary, #2E8B57);
                padding-bottom: 20px;
            }
            
            .song-title {
                font-size: 2.2em;
                color: var(--unclelele-primary, #2E8B57);
                margin: 0 0 10px 0;
                font-weight: bold;
            }
            
            .song-artist {
                font-size: 1.3em;
                color: #666;
                font-style: italic;
                margin: 0 0 15px 0;
            }
            
            .song-meta {
                display: flex;
                justify-content: center;
                gap: 20px;
                flex-wrap: wrap;
                font-size: 0.9em;
                color: #555;
            }
            
            .meta-item {
                background: rgba(46, 139, 87, 0.1);
                padding: 5px 12px;
                border-radius: 6px;
                font-weight: bold;
            }
            
            .chords-section {
                margin-bottom: 30px;
            }
            
            .chords-section h3 {
                color: var(--unclelele-primary, #2E8B57);
                border-bottom: 1px solid #ddd;
                padding-bottom: 8px;
                margin-bottom: 15px;
                font-size: 1.2em;
            }
            
            .chord-diagrams {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
                gap: 20px;
                margin-bottom: 20px;
            }
            
            .chord-diagram-wrapper {
                text-align: center;
                background: rgba(255, 248, 220, 0.5);
                padding: 15px;
                border-radius: 8px;
                border: 1px solid #e0e0e0;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
            }
            
            .chord-diagram {
                text-align: center;
                background: rgba(255, 248, 220, 0.5);
                padding: 15px;
                border-radius: 8px;
                border: 1px solid #e0e0e0;
            }
            
            .chord-name {
                font-weight: bold;
                font-size: 1.1em;
                margin-bottom: 8px;
                padding: 4px 8px;
                border-radius: 4px;
                color: white;
                text-shadow: 1px 1px 2px rgba(0,0,0,0.3);
            }
            
            /* Chord color coding */
            .chord-name.chord-c {
                background-color: #DC2626; /* Red for C */
            }
            
            .chord-name.chord-g {
                background-color: #16A34A; /* Green for G */
            }
            
            .chord-name.chord-f {
                background-color: #EAB308; /* Yellow for F */
                color: #000; /* Black text on yellow */
                text-shadow: none;
            }
            
            .chord-name.chord-am {
                background-color: #2563EB; /* Blue for Am */
            }
            
            /* Default color for other chords */
            .chord-name:not(.chord-c):not(.chord-g):not(.chord-f):not(.chord-am) {
                background-color: var(--unclelele-primary, #2E8B57);
            }
            
            .chord-frets {
                font-family: 'Courier New', monospace;
                font-size: 0.9em;
                line-height: 1.2;
                background: white;
                padding: 8px;
                border-radius: 4px;
                border: 1px solid #ddd;
            }
            
            .chord-difficulty {
                font-size: 0.8em;
                color: #666;
                font-style: italic;
                margin-top: 5px;
            }
            
            .strumming-section {
                margin-bottom: 30px;
            }
            
            .strumming-pattern {
                font-family: 'Courier New', monospace;
                font-size: 1.1em;
                background: rgba(247, 147, 30, 0.1);
                padding: 15px;
                border-radius: 8px;
                border-left: 4px solid var(--unclelele-accent, #F7931E);
                margin-bottom: 10px;
            }
            
            .lyrics-section {
                margin-bottom: 30px;
            }
            
            .lyrics-content {
                font-size: 1.1em;
                line-height: 2.5;
                color: #333;
            }
            
            .lyrics-line {
                position: relative;
                margin: 0.5em 0;
                min-height: 2em;
                display: block;
            }
            
            .chord-above {
                position: absolute;
                top: -1.2em;
                font-weight: bold;
                font-size: 0.85em;
                font-family: 'Courier New', monospace;
                z-index: 1;
                line-height: 20px;
                padding: 2px 4px;
                border-radius: 3px;
                color: white;
                text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
            }
            
            /* Inline chord color coding */
            .chord-above.chord-c {
                background-color: #DC2626; /* Red for C */
            }
            
            .chord-above.chord-g {
                background-color: #16A34A; /* Green for G */
            }
            
            .chord-above.chord-f {
                background-color: #EAB308; /* Yellow for F */
                color: #000; /* Black text on yellow */
                text-shadow: none;
            }
            
            .chord-above.chord-am {
                background-color: #2563EB; /* Blue for Am */
            }
            
            /* Default color for other chords */
            .chord-above:not(.chord-c):not(.chord-g):not(.chord-f):not(.chord-am) {
                background-color: var(--unclelele-primary, #2E8B57);
            }
            
            .verse, .chorus, .bridge, .intro, .outro, .pre-chorus {
                margin-bottom: 25px;
                padding: 15px;
                border-left: 3px solid;
                background: rgba(255,255,255,0.8);
            }
            
            .verse {
                border-left-color: var(--unclelele-secondary, #98D8C8);
                background: rgba(152, 216, 200, 0.1);
            }
            
            .chorus {
                border-left-color: var(--unclelele-accent, #F7931E);
                background: rgba(247, 147, 30, 0.1);
                font-weight: bold;
            }
            
            .bridge {
                border-left-color: var(--unclelele-primary, #2E8B57);
                background: rgba(46, 139, 87, 0.1);
                font-style: italic;
            }
            
            .intro {
                border-left-color: #9C27B0;
                background: rgba(156, 39, 176, 0.1);
                font-style: italic;
                opacity: 0.9;
            }
            
            .outro {
                border-left-color: #FF5722;
                background: rgba(255, 87, 34, 0.1);
                font-weight: bold;
                border-width: 4px;
            }
            
            .pre-chorus {
                border-left-color: #FF9800;
                background: rgba(255, 152, 0, 0.1);
                font-weight: 500;
                border-left-style: dashed;
            }
            
            .section-label {
                font-size: 0.9em;
                color: #666;
                font-weight: bold;
                text-transform: uppercase;
                margin-bottom: 8px;
                letter-spacing: 1px;
            }
            
            .sheet-footer {
                padding: 20px 30px;
                background: #f8f9fa;
                text-align: center;
                color: #666;
                font-size: 0.9em;
            }
            
            .sheet-footer a {
                color: var(--unclelele-primary, #2E8B57);
                text-decoration: none;
                font-weight: bold;
            }
            
            .sheet-footer a:hover {
                text-decoration: underline;
            }
            
            /* Print-only footer (hidden by default) */
            .print-only {
                display: none;
            }
            
            .print-only-footer {
                position: fixed;
                bottom: 0;
                left: 0;
                right: 0;
                background: transparent;
                padding: 10px 0;
                text-align: center;
            }
            
            .print-footer-content {
                font-size: 0.7em;
                color: #666;
                font-family: Arial, sans-serif;
            }
            
            .print-separator {
                margin: 0 8px;
            }
            
            @media (max-width: 768px) {
                .song-sheet {
                    padding: 20px;
                }
                
                .song-title {
                    font-size: 1.8em;
                }
                
                .chord-diagrams {
                    grid-template-columns: repeat(2, 1fr);
                    gap: 15px;
                }
                
                .sheet-header {
                    flex-direction: column;
                }
                
                .song-meta {
                    flex-direction: column;
                    gap: 10px;
                }
            }
            
            /* Print Styles */
            @media print {
                /* Hide non-print elements */
                .no-print {
                    display: none !important;
                }
                
                /* Show print-only elements */
                .print-only {
                    display: block !important;
                }
                
                /* Page setup */
                @page {
                    size: letter;
                    margin: 0.75in 0.5in 1in 0.5in; /* top right bottom left */
                }
                
                /* Container adjustments */
                .song-sheet-container {
                    box-shadow: none;
                    border-radius: 0;
                    margin: 0;
                    background: white;
                    width: 100%;
                    height: 100vh;
                    display: flex;
                    flex-direction: column;
                }
                
                /* Main content area */
                .song-sheet {
                    flex: 1;
                    padding: 0;
                    margin: 0;
                    max-width: none;
                    min-height: auto;
                    font-size: 11pt;
                    line-height: 1.3;
                    color: black;
                    background: white;
                }
                
                /* Typography improvements for print */
                .song-title {
                    font-size: 18pt;
                    color: black !important;
                    margin-bottom: 8pt;
                }
                
                .song-artist {
                    font-size: 12pt;
                    color: black !important;
                    margin-bottom: 12pt;
                }
                
                .song-meta {
                    margin-bottom: 18pt;
                    font-size: 9pt;
                }
                
                .meta-item {
                    background: transparent !important;
                    border: 1px solid black;
                    color: black !important;
                    padding: 3px 8px;
                    margin: 2px;
                    display: inline-block;
                }
                
                /* Section headers */
                h3 {
                    font-size: 12pt;
                    color: black !important;
                    margin: 12pt 0 8pt 0;
                    border-bottom: 1px solid black !important;
                    padding-bottom: 3pt;
                }
                
                /* Chord diagrams optimization */
                .chord-diagrams {
                    grid-template-columns: repeat(4, 1fr);
                    gap: 12px;
                    margin-bottom: 12pt;
                    page-break-inside: avoid;
                }
                
                .chord-diagram-wrapper {
                    background: transparent !important;
                    border: 1px solid black;
                    padding: 8pt;
                    page-break-inside: avoid;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    justify-content: center;
                    text-align: center;
                }
                
                .chord-diagram {
                    background: transparent !important;
                    border: 1px solid black;
                    padding: 8pt;
                    page-break-inside: avoid;
                }
                
                .chord-name {
                    font-size: 10pt;
                    font-weight: bold;
                    color: white !important;
                    text-shadow: none !important;
                    padding: 2pt 4pt;
                    border-radius: 2pt;
                }
                
                /* Print chord colors - ensure they show */
                .chord-name.chord-c {
                    background-color: #DC2626 !important; /* Red for C */
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-name.chord-g {
                    background-color: #16A34A !important; /* Green for G */
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-name.chord-f {
                    background-color: #EAB308 !important; /* Yellow for F */
                    color: black !important;
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-name.chord-am {
                    background-color: #2563EB !important; /* Blue for Am */
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-name:not(.chord-c):not(.chord-g):not(.chord-f):not(.chord-am) {
                    background-color: #2E8B57 !important;
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-frets {
                    font-size: 8pt;
                    background: transparent !important;
                    border: none;
                    color: black;
                }
                
                .chord-difficulty {
                    font-size: 7pt;
                    color: #333 !important;
                }
                
                /* Strumming pattern */
                .strumming-pattern {
                    background: transparent !important;
                    border: 2px solid black;
                    border-left: 4px solid black !important;
                    color: black !important;
                    font-size: 10pt;
                    padding: 8pt;
                    margin-bottom: 8pt;
                }
                
                /* Lyrics sections */
                .verse, .chorus, .bridge, .intro, .outro, .pre-chorus {
                    background: transparent !important;
                    border-left: 3px solid black !important;
                    margin-bottom: 12pt;
                    padding: 6pt 8pt;
                    page-break-inside: avoid;
                }
                
                .chorus {
                    border-left: 4px solid black !important;
                    font-weight: bold;
                }
                
                .outro {
                    border-left: 5px solid black !important;
                    font-weight: bold;
                }
                
                .pre-chorus {
                    border-left: 2px dashed black !important;
                    font-weight: 500;
                }
                
                .intro {
                    font-style: italic;
                    opacity: 1;
                }
                
                .bridge {
                    font-style: italic;
                }
                
                .section-label {
                    font-size: 8pt;
                    color: black !important;
                    font-weight: bold;
                    margin-bottom: 4pt;
                }
                
                /* Lyrics content */
                .lyrics-content {
                    font-size: 10pt;
                    line-height: 2.2;
                    color: black !important;
                }
                
                .lyrics-line {
                    position: relative;
                    margin: 4pt 0;
                    min-height: 14pt;
                    display: block;
                }
                
                /* Chord markings in lyrics */
                .chord-above {
                    position: absolute;
                    top: -10pt;
                    font-weight: bold;
                    font-size: 7pt;
                    font-family: 'Courier New', monospace;
                    z-index: 1;
                    padding: 1pt 2pt;
                    border-radius: 1pt;
                    color: white !important;
                    text-shadow: none !important;
                }
                
                /* Print inline chord colors */
                .chord-above.chord-c {
                    background-color: #DC2626 !important; /* Red for C */
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-above.chord-g {
                    background-color: #16A34A !important; /* Green for G */
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-above.chord-f {
                    background-color: #EAB308 !important; /* Yellow for F */
                    color: black !important;
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-above.chord-am {
                    background-color: #2563EB !important; /* Blue for Am */
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                .chord-above:not(.chord-c):not(.chord-g):not(.chord-f):not(.chord-am) {
                    background-color: #2E8B57 !important;
                    -webkit-print-color-adjust: exact;
                    color-adjust: exact;
                }
                
                /* Lyrics text */
                .lyrics-content p {
                    margin: 3pt 0;
                    font-size: 10pt;
                    line-height: 2.2;
                }
                
                /* Print footer styling */
                .print-only-footer {
                    position: fixed;
                    bottom: 0.25in;
                    left: 0;
                    right: 0;
                    text-align: center;
                    z-index: 1000;
                }
                
                .print-footer-content {
                    font-size: 8pt;
                    color: #555;
                    font-family: Arial, sans-serif;
                }
                
                .print-url {
                    font-weight: bold;
                }
                
                .print-separator {
                    margin: 0 6px;
                    color: #999;
                }
                
                .print-branding {
                    font-style: italic;
                }
                
                /* Page break controls */
                .chords-section,
                .strumming-section,
                .lyrics-section,
                .verse,
                .chorus, 
                .bridge,
                .intro,
                .outro,
                .pre-chorus {
                    page-break-inside: avoid;
                }
                
                /* Ensure no orphaned section headers */
                h3 {
                    page-break-after: avoid;
                }
                
                /* Prevent widows and orphans */
                p {
                    orphans: 2;
                    widows: 2;
                }
                
                /* Print quality enhancements */
                * {
                    -webkit-print-color-adjust: exact !important;
                    color-adjust: exact !important;
                }
            }
        `;
        
        super(template, styles);
        
        this.currentSong = null;
        this.setupEventListeners();
    }
    
    static get observedAttributes() {
        return ['song-id'];
    }
    
    attributeChangedCallback(name, oldValue, newValue) {
        if (name === 'song-id' && newValue !== oldValue) {
            this.loadSong(newValue);
        }
    }
    
    setupEventListeners() {
        const backBtn = this.shadowRoot.getElementById('back-search');
        const shareBtn = this.shadowRoot.getElementById('share-btn');
        const printBtn = this.shadowRoot.getElementById('print-btn');
        const fullscreenBtn = this.shadowRoot.getElementById('fullscreen-btn');
        const gigsoLink = this.shadowRoot.getElementById('gigso-link');
        
        backBtn.addEventListener('click', () => {
            this.dispatchEvent(new CustomEvent('navigate-back', {
                detail: { to: 'search' },
                bubbles: true
            }));
        });
        
        shareBtn.addEventListener('click', () => {
            this.shareSong();
        });
        
        printBtn.addEventListener('click', () => {
            window.print();
        });
        
        fullscreenBtn.addEventListener('click', () => {
            this.toggleFullscreen();
        });
        
        gigsoLink.addEventListener('click', (e) => {
            e.preventDefault();
            window.open('index.html', '_blank');
        });
    }
    
    loadSong(songId) {
        const song = UkuleleSongLibrary.songs.find(s => s.id === songId);
        if (!song) {
            console.error('Song not found:', songId);
            return;
        }
        
        this.currentSong = song;
        this.renderSong();
    }
    
    renderSong() {
        if (!this.currentSong) return;
        
        const song = this.currentSong;
        const contentDiv = this.shadowRoot.getElementById('song-content');
        
        // Extract unique chords from inline notation in lyrics
        const uniqueChords = this.extractChordsFromLyrics(song.lyrics);
        const chordDiagrams = uniqueChords.map(chordName => {
            const chordData = ChordLibrary.chords[chordName]?.ukulele;
            return { name: chordName, data: chordData };
        }).filter(chord => chord.data);
        
        contentDiv.innerHTML = `
            <div class="song-header">
                <h1 class="song-title">${song.title}</h1>
                <p class="song-artist">by ${song.artist}</p>
                <div class="song-meta">
                    <span class="meta-item">Key: ${song.key}</span>
                    <span class="meta-item">Difficulty: ${song.difficulty}</span>
                    <span class="meta-item">Genre: ${song.genre}</span>
                    ${song.tempo ? `<span class="meta-item">Tempo: ${song.tempo} BPM</span>` : ''}
                </div>
            </div>
            
            ${chordDiagrams.length > 0 ? `
            <div class="chords-section">
                <h3>🎼 Chord Diagrams</h3>
                <div class="chord-diagrams" id="chord-diagrams-container">
                    <!-- Chord diagrams will be inserted here -->
                </div>
            </div>
            ` : ''}
            
            ${song.strummingPattern ? `
            <div class="strumming-section">
                <h3>🎵 Strumming Pattern</h3>
                <div class="strumming-pattern">
                    ${song.strummingPattern}
                </div>
                ${song.strummingNotes ? `<p><em>${song.strummingNotes}</em></p>` : ''}
            </div>
            ` : ''}
            
            <div class="lyrics-section">
                <h3>🎤 Lyrics & Chords</h3>
                <div class="lyrics-content">
                    ${this.formatLyrics(song.lyrics)}
                </div>
            </div>
        `;
        
        // After setting innerHTML, render chord diagrams using the chord diagram component
        if (chordDiagrams.length > 0) {
            this.renderChordDiagrams(chordDiagrams);
        }
    }
    
    extractChordsFromLyrics(lyrics) {
        if (!lyrics) return [];
        
        // Extract all chord markers like {C}, {Am}, {F}, etc.
        const chordMatches = lyrics.match(/\{([^}]+)\}/g);
        if (!chordMatches) return [];
        
        // Remove brackets and get unique chords
        const chords = chordMatches.map(match => match.replace(/[{}]/g, ''));
        return [...new Set(chords)];
    }
    
    renderChordDiagrams(chordDiagrams) {
        const container = this.shadowRoot.getElementById('chord-diagrams-container');
        if (!container) return;
        
        // Clear existing content
        container.innerHTML = '';
        
        // Create and append chord diagram components
        chordDiagrams.forEach(chordInfo => {
            const chordWrapper = document.createElement('div');
            chordWrapper.className = 'chord-diagram-wrapper';
            const chordClass = this.getChordColorClass(chordInfo.name);
            chordWrapper.innerHTML = `
                <div class="chord-name ${chordClass}">${chordInfo.name}</div>
                <chord-diagram chord="${chordInfo.name}" instrument="ukulele"></chord-diagram>
            `;
            container.appendChild(chordWrapper);
        });
    }
    
    renderChordDiagram(chord) {
        if (!chord.data) return '';
        
        const fretDisplay = this.formatFretPositions(chord.data.positions);
        
        return `
            <div class="chord-diagram">
                <div class="chord-name">${chord.name}</div>
                <div class="chord-frets">${fretDisplay}</div>
                <div class="chord-difficulty">${chord.data.difficulty}</div>
            </div>
        `;
    }
    
    formatFretPositions(positions) {
        // Format ukulele fret positions for display
        const strings = ['A', 'E', 'C', 'G']; // Ukulele strings (4th to 1st)
        
        let display = '';
        display += '    ' + strings.join('   ') + '\n'; // String names
        display += '  |---|---|---|---|\n'; // Nut
        
        // Find the maximum fret to determine how many frets to show
        const maxFret = Math.max(...positions.filter(p => p > 0), 3);
        
        for (let fret = 1; fret <= maxFret; fret++) {
            display += `${fret} |`;
            positions.forEach(pos => {
                if (pos === fret) {
                    display += ' ● |';
                } else if (pos === 0 && fret === 1) {
                    display += ' ○ |'; // Open string
                } else {
                    display += '   |';
                }
            });
            display += '\n';
        }
        
        return display;
    }
    
    formatLyrics(lyrics) {
        if (!lyrics) return '<p>Lyrics not available</p>';
        
        const lines = lyrics.split('\n');
        let formattedLyrics = '';
        let currentSection = null;
        
        lines.forEach(line => {
            const trimmedLine = line.trim();
            
            // Check for section markers
            if (trimmedLine.match(/^\[(verse|chorus|bridge|intro|outro|pre-chorus)\s*\d*\]$/i)) {
                const sectionType = trimmedLine.toLowerCase()
                    .replace(/[\[\]]/g, '')
                    .replace(/\s*\d*$/, '')
                    .replace('-', '-'); // Keep pre-chorus hyphen
                currentSection = sectionType;
                formattedLyrics += `<div class="${sectionType}">`;
                formattedLyrics += `<div class="section-label">${trimmedLine.replace(/[\[\]]/g, '')}</div>`;
                return;
            }
            
            // Empty lines end sections
            if (!trimmedLine && currentSection) {
                formattedLyrics += '</div>';
                currentSection = null;
                return;
            }
            
            // Skip empty lines
            if (!trimmedLine) {
                return;
            }
            
            // Parse inline chords format: {C}word {Am}another word
            let chordsHtml = '';
            let lyricsText = '';
            let currentPosition = 0;
            
            // Split by chord markers and process
            const parts = trimmedLine.split(/(\{[^}]+\})/);
            
            parts.forEach(part => {
                if (part.match(/^\{[^}]+\}$/)) {
                    // This is a chord marker like {C} or {Am}
                    const chord = part.replace(/[{}]/g, '');
                    const chordClass = this.getChordColorClass(chord);
                    const leftPosition = currentPosition * 0.6; // Approximate character width in ems
                    chordsHtml += `<span class="chord-above ${chordClass}" style="left: ${leftPosition}em;">${chord}</span>`;
                } else if (part) {
                    // This is lyrics text
                    lyricsText += part;
                    currentPosition += part.length;
                }
            });
            
            // Create the line with relative positioning container
            formattedLyrics += `<div class="lyrics-line">${chordsHtml}${lyricsText}</div>`;
        });
        
        // Close any remaining open section
        if (currentSection) {
            formattedLyrics += '</div>';
        }
        
        return formattedLyrics;
    }
    
    getChordColorClass(chordName) {
        // Normalize chord name to handle variations
        const normalizedChord = chordName.toLowerCase().trim();
        
        switch (normalizedChord) {
            case 'c':
                return 'chord-c';
            case 'g':
                return 'chord-g';
            case 'f':
                return 'chord-f';
            case 'am':
            case 'a minor':
                return 'chord-am';
            default:
                return '';
        }
    }
    
    shareSong() {
        if (!this.currentSong) return;
        
        const songUrl = `${window.location.origin}${window.location.pathname}#song/${this.currentSong.id}`;
        
        // Try to use the Web Share API if available
        if (navigator.share) {
            navigator.share({
                title: `${this.currentSong.title} - Ukulele Song Sheet`,
                text: `Check out this ukulele song sheet for "${this.currentSong.title}" by ${this.currentSong.artist}`,
                url: songUrl
            }).catch(err => console.log('Share failed:', err));
        } else {
            // Fallback: copy to clipboard
            navigator.clipboard.writeText(songUrl).then(() => {
                // Show temporary success message
                const shareBtn = this.shadowRoot.getElementById('share-btn');
                const originalText = shareBtn.textContent;
                shareBtn.textContent = '✅ Copied!';
                shareBtn.style.background = '#10B981';
                
                setTimeout(() => {
                    shareBtn.textContent = originalText;
                    shareBtn.style.background = '#3B82F6';
                }, 2000);
            }).catch(err => {
                // Fallback: prompt with URL
                prompt('Copy this URL to share the song:', songUrl);
            });
        }
    }
    
    toggleFullscreen() {
        const container = this.shadowRoot.querySelector('.song-sheet-container');
        
        if (!document.fullscreenElement) {
            container.requestFullscreen().catch(err => {
                console.error('Error attempting to enable fullscreen:', err);
            });
        } else {
            document.exitFullscreen();
        }
    }
}

customElements.define('song-sheet', SongSheet);